#!/usr/bin/env bash
# Destroy all AWS resources created by Terraform for this stack.
#
# Usage:
#   ./destroy.sh [dev]
#   ./destroy.sh dev -y              # no confirmation
#   DEPLOY_DESTROY_YES=1 ./destroy.sh dev
#
# WARNING: Deletes RDS, EFS data, ECR images (if force_delete), etc.
#
set -euo pipefail

ENV="dev"
AUTO_YES=0
if [[ "${DEPLOY_DESTROY_YES:-}" == "1" ]]; then
  AUTO_YES=1
fi
while [[ $# -gt 0 ]]; do
  case "$1" in
    -y|--yes) AUTO_YES=1; shift ;;
    -*) echo "Unknown option: $1" >&2; exit 1 ;;
    *) ENV="$1"; shift ;;
  esac
done

INFRA="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
source "$INFRA/lib/common.sh"

require_commands terraform aws

ensure_tfvars "$ENV"
load_deploy_env "$ENV"

if [[ "$AUTO_YES" != "1" ]]; then
  echo "This will DESTROY all Terraform-managed resources for env=$ENV"
  echo "  - VPC, EC2, ALB, RDS (database), ElastiCache, EFS (artifacts), ECR repos, Secrets"
  read -r -p "Type the environment name to confirm ($ENV): " confirm
  if [[ "$confirm" != "$ENV" ]]; then
    echo "Aborted."
    exit 1
  fi
fi

echo "==> Terraform init"
"$INFRA/Scripts/terraform-init.sh" "$ENV"

echo "==> Terraform destroy"
cd "$(tf_dir)"
terraform destroy \
  -var-file="environments/${ENV}/terraform.tfvars" \
  -var="environment=${ENV}" \
  -auto-approve

STATE_FILE="$(deploy_state_file "$ENV")"
if [[ -f "$STATE_FILE" ]]; then
  rm -f "$STATE_FILE"
  echo "Removed $STATE_FILE"
fi

INV="$INFRA/Ansible/inventory/aws_ec2.yml"
if [[ -f "$INV" ]] && grep -q "Auto-generated by deploy.sh" "$INV" 2>/dev/null; then
  rm -f "$INV"
  echo "Removed generated inventory $INV"
fi

echo "==> Destroy complete for env=$ENV"
